//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointisData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pointage
    {
        public long PointageID { get; set; }
        public System.DateTime Jour { get; set; }
        public System.TimeSpan HeureEntree { get; set; }
        public System.TimeSpan HeureSortie { get; set; }
        public Nullable<long> EmployesID { get; set; }
    
        public Employes Employes { get; set; }
        //public virtual Employes Employes { get; set; }
    }
}
